[package]
name = "muxd"
version = "0.0.1"
edition = "2021"

[dependencies]
mux-core = { path = "../mux-core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
crossbeam-channel = "0.5"
ctrlc = "3.4"